# Generated by Django 4.2.6 on 2024-11-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
