# Generated by Django 4.2.6 on 2024-11-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_remove_profile_first_name_remove_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
    ]
